import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/shared/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col container m-auto px-10 py-4">
          <Navbar/>
          {children}
        </div>
      </body>
    </html>
  );
}
